config/routes.rb
Boids::Application.routes.draw do
  root :to => 'flocks#homepage'
  resources :flocks

end

app/models/flock.rb
class Flock < ActiveRecord::Base
  attr_accessible :align, :avoid, :boids, :boidsize, :center, :goalseek, :height, :jitter, :name, :width
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  protect_from_forgery
end

app/controllers/flocks_controller.rb
class FlocksController < ApplicationController
  inherit_resources
  respond_to :html, :json
  actions :index, :show, :new, :create, :update, :destroy, :homepage
  def homepage
      p "home"
      @flock = Flock.find(1)
      respond_with @flock
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flocks_helper.rb
module FlocksHelper
end

app/views/flocks/_form.html.haml
= form_for @flock do |f|
  -if @flock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@flock.errors.count, "error")} prohibited this flock from being saved:"
      %ul
        - @flock.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :avoid
    = f.text_field :avoid
  .field
    = f.label :align
    = f.text_field :align
  .field
    = f.label :center
    = f.text_field :center
  .field
    = f.label :jitter
    = f.text_field :jitter
  .field
    = f.label :goalseek
    = f.text_field :goalseek
  .field
    = f.label :boids
    = f.number_field :boids
  .field
    = f.label :boidsize
    = f.number_field :boidsize
  .field
    = f.label :width
    = f.number_field :width
  .field
    = f.label :height
    = f.number_field :height
  .actions
    = f.submit 'Save'

app/views/flocks/_show.html.haml
#flockwrap

  #flock 
    %canvas#cv{ width: @flock.width, height: @flock.height }
  #editwrap
    // %h1= "Boids"
    // %h2 Javascript Flocking Algorithm
    #header
      %h1.flock_title= "#{@flock.name}"
      %a#editbutton.icon-cog
        %span
          Settings
    #controls.reveal.hide
      %a#slower.icon-fast-bw{:title => 'Slower'}
      %a#start.icon-play.hide{:title => 'Start the simulation'}
        Play
      %a#stop.icon-pause{:title => 'Stop the simulation'}
        Pause
      %a#faster.icon-fast-fw{:title => 'Faster'}
      %a#initialize.icon-shuffle{:title => 'Intitialize'}
      %a#step.icon-to-end{:title => 'Step Forward'}
      %a#toggle_halo.icon-target{:title => 'Show perimeters'}
      // TODO: new icon
      %a#redraw.icon-record{:title => 'Redraw'}
      %a#console_debug.icon-doc-text{:title => 'Console Debug'}
      %a#show_numbers.icon-info-circle{:title => 'Labels'}
      .icon.icon-plus-circle{:title => 'New Flock'}= link_to '', new_flock_path
      .icon{:title => 'Back to index'}= link_to 'Back', flocks_path
    #details.reveal.hide
      %a#avoid.link= "Avoid: #{@flock.avoid}"
      %a#align.link= "Align: #{@flock.align}"
      %a#center.link= "Center: #{@flock.center}"
      %a#jitter.link= "Jitter: #{@flock.jitter}"
      %a#goalseek.link= "Goalseek: #{@flock.goalseek}"
    .clearfix
  %script
    != "window.flock = #{@flock.to_json};"
    != "addLoadEvent(function(){window.flock_run = make_flock(window.flock).initialize().start();});"
    != "addLoadEvent(function(){window.flock_run.offset = $(\"#cv\").offset();});"

app/views/flocks/edit.html.haml
%h1 Editing flock

= render 'form'

= link_to 'Show', @flock
\|
= link_to 'Back', flocks_path

app/views/flocks/homepage.html.haml
= render :partial => "flocks/show", :locals => { flock: @flock }

app/views/flocks/index.html.haml
%h1 Listing flocks

%table
  %tr
    %th Name
    %th Avoid
    %th Align
    %th Center
    %th Jitter
    %th Goalseek
    %th Boids
    %th Boidsize
    %th Width
    %th Height
    %th
    %th

  - @flocks.each do |flock|
    %tr
      %td= flock.name
      %td= flock.avoid
      %td= flock.align
      %td= flock.center
      %td= flock.jitter
      %td= flock.goalseek
      %td= flock.boids
      %td= flock.boidsize
      %td= flock.width
      %td= flock.height
      %td= link_to 'Show', flock

%br

= link_to 'New Flock', new_flock_path

app/views/flocks/new.html.haml
%h1 New flock

= render 'form'

= link_to 'Back', flocks_path

app/views/flocks/show.html.haml
%p#notice= notice
#flock 
  #header
    %b Name:
    = @flock.name
    %b Width:
    = @flock.width
    %b Height:
    = @flock.height
    %b Boids:
    = @flock.boids
    %b Boidsize:
    = @flock.boidsize
  #controls 
    %a#start.link Start
    %a#stop.link Stop
    %a#toggle_halo.link Halo
    %a#initialize.link Reset
    %a#step.link Step
    %a#redraw.link Redraw
    %a#faster.link Faster
    %a#slower.link Slower
    %a#console_debug.link Console Debug
    %a#show_numbers.link Show Numbers
    .link= link_to 'New', new_flock_path
    .link= link_to 'Back', flocks_path
  #details
    %p#avoid.link
      %b Avoid:
      = @flock.avoid
    %p#align.link
      %b Align:
      = @flock.align
    %p#center.link
      %b Center:
      = @flock.center
    %p#jitter.link
      %b Jitter:
      = @flock.jitter
    %p#goalseek.link
      %b Goalseek:
      = @flock.goalseek
  %canvas#cv{ width: @flock.width, height: @flock.height }
  %script
    != "window.flock = #{@flock.to_json};"
    != "addLoadEvent(function(){window.flock_run = make_flock(window.flock).initialize().start();});"
    != "addLoadEvent(function(){window.flock_run.offset = $(\"#cv\").offset();});"


#nav

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{'http-equiv' => 'Content-Type', 
        :content => 'text/html; charset=UTF-8'}/
    :javascript
      var fns=[];function addLoadEvent(func){fns.push(func);}
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    %div{ id: "#{params[:controller]}_#{params[:action]}", class: [ "outermost", params[:controller], params[:action] ] }
      = yield
    = javascript_include_tag "application"
    :javascript
      $(document).ready(function(){
        for( i=0; i< fns.length; ++i ){  
          //console.debug([i,fns[i]]);
          $(fns[i]); 
        }   
      }); 